Fixes #573 Error stopping/starting an app with Probe 2.4 under Tomcat 8
org.apache.catalina.Context.getAvailable() were deprecated in Tomcat 7
and a note were added stating it will be removed in Tomcat 8. Therefore,
the java.lang.NoSuchMethodError at
org.apache.catalina.Context.getAvailable().